spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    gcp:
      storage:
        credentials:
          location: ${gcp.location}
        project-id: ${gcp.project.id}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB